"""Описание изменения

Revision ID: 14d2cf29f859
Revises: fb8c2b5cd98c
Create Date: 2024-12-14 23:14:08.790737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d2cf29f859'
down_revision: Union[str, None] = 'fb8c2b5cd98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
